"""add user name and email to order table

Revision ID: 3114a3df5746
Revises: 638000244c83
Create Date: 2025-12-12 16:07:22.019678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3114a3df5746'
down_revision: Union[str, Sequence[str], None] = '638000244c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('user_name', sa.String(), nullable=False))
    op.add_column('order', sa.Column('user_email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'user_email')
    op.drop_column('order', 'user_name')
    # ### end Alembic commands ###
