"""remove fee_type from order

Revision ID: 638000244c83
Revises: f68c933c0a11
Create Date: 2025-12-11 09:43:58.836352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '638000244c83'
down_revision: Union[str, Sequence[str], None] = 'f68c933c0a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'fee_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('fee_type', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
