"""init

Revision ID: f68c933c0a11
Revises: 
Create Date: 2025-12-08 17:04:17.971164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68c933c0a11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('auction', sa.Enum('COPART', 'IAAI', name='auctionenum'), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_value', sa.Integer(), nullable=False),
    sa.Column('invoice_type', sa.Enum('DEFAULT', name='invoicetypeenum'), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=False),
    sa.Column('vin', sa.String(), nullable=False),
    sa.Column('vehicle_name', sa.String(), nullable=False),
    sa.Column('keys', sa.Boolean(), nullable=False),
    sa.Column('damage', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('tracking_link', sa.String(), nullable=True),
    sa.Column('auto_generated', sa.Boolean(), nullable=False),
    sa.Column('fee_type', sa.String(), nullable=False),
    sa.Column('delivery_status', sa.Enum('WON', 'PORT_CHOSEN', 'INVOICE_ADDED', 'TRACKING_ADDED', 'VEHICLE_IN_CUSTOM_AGENCY', 'CUSTOM_INVOICE_ADDED', 'DELIVERED', name='orderstatusenum'), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_state', sa.String(), nullable=True),
    sa.Column('location_postal_code', sa.String(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('destination_name', sa.String(), nullable=True),
    sa.Column('terminal_id', sa.Integer(), nullable=False),
    sa.Column('terminal_name', sa.String(), nullable=False),
    sa.Column('fee_type_id', sa.Integer(), nullable=False),
    sa.Column('fee_type_name', sa.String(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id'),
    sa.UniqueConstraint('vin')
    )
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_table('custom_invoice',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AVAILABLE', name='custominvoicestatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_custom_invoice_id'), 'custom_invoice', ['id'], unique=False)
    op.create_table('invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('is_extra_fee', sa.Boolean(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_status_history',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WON', 'PORT_CHOSEN', 'INVOICE_ADDED', 'TRACKING_ADDED', 'VEHICLE_IN_CUSTOM_AGENCY', 'CUSTOM_INVOICE_ADDED', 'DELIVERED', name='orderstatusenum'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_id'), 'order_status_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_status_history_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_table('invoice_item')
    op.drop_index(op.f('ix_custom_invoice_id'), table_name='custom_invoice')
    op.drop_table('custom_invoice')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
